name: Hello CI

on:
  push:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello CI"

      - name: Show current date and user
        run: |
          date
          whoami

      - name: Create a file
        run: touch test.txt

      - name: List files
        run: ls -la
